---
- hosts: all
  roles:
  - { role: roles/common }
  - { role: roles/contrib/docker }

- hosts: consul
  roles:
    - { role: roles/consul }
  tags:
    - consul

- hosts: nomad
    - { role: roles/nomad }
  tags:
    - nomad

